version: '3'
services:
  react:
    container_name: react-container
    build: ./client_side
    image: react-image
    restart: always
    ports:
      - "3000:3000"
    environment:
      EXPRESS_URL: "http://localhost:3001"
    depends_on:
      - express
      - mongo
  express:
    container_name: express-container
    build: ./movieProject
    image: express-image
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  mongo:
    container_name: mongo-container
    build: ./mongodb
    image: mongo-image
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./mongodb/mongo-data:/data/db